"""add category types and categories

Two tables: a taxonomy, and the tree of categories inside it.

Three foreign key behaviours, each chosen rather than defaulted:

- `created_by` / `updated_by` are `SET NULL`, so deleting the administrator
  who made a category does not delete the category with them.
- `category_type_id` is `RESTRICT`, so removing a taxonomy cannot silently
  take its whole tree. The service checks first and says what is in the way.
- `parent_category_id` is `RESTRICT` for the same reason one level down.

Both tables carry `deleted_at` from `SoftDeleteMixin`, which the column list
in the request did not name. It is the project's convention for anything
content can point at: a category that is deleted while pages are filed under
it has to stay resolvable, and `status` answers a different question -
"should this be offered for new content?" rather than "does it still exist?".

Revision ID: b273e1cb0395
Revises: 75c717954d14
Create Date: 2026-08-15 18:00:06.766655

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b273e1cb0395"
down_revision: str | None = "75c717954d14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category_types",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_category_types_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_category_types_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category_types")),
        sa.UniqueConstraint("name", name=op.f("uq_category_types_name")),
    )
    op.create_index(
        op.f("ix_category_types_deleted_at"),
        "category_types",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_category_types_slug"), "category_types", ["slug"], unique=True
    )
    op.create_index(
        op.f("ix_category_types_status"), "category_types", ["status"], unique=False
    )
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_type_id", sa.UUID(), nullable=False),
        sa.Column("parent_category_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_type_id"],
            ["category_types.id"],
            name=op.f("fk_categories_category_type_id_category_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_categories_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_category_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_categories_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("category_type_id", "name", name="uq_categories_type_name"),
    )
    op.create_index(
        op.f("ix_categories_category_type_id"),
        "categories",
        ["category_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_categories_deleted_at"), "categories", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_categories_parent_category_id",
        "categories",
        ["parent_category_id"],
        unique=False,
    )
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.create_index(
        op.f("ix_categories_status"), "categories", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categories_status"), table_name="categories")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_index("ix_categories_parent_category_id", table_name="categories")
    op.drop_index(op.f("ix_categories_deleted_at"), table_name="categories")
    op.drop_index(op.f("ix_categories_category_type_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_category_types_status"), table_name="category_types")
    op.drop_index(op.f("ix_category_types_slug"), table_name="category_types")
    op.drop_index(op.f("ix_category_types_deleted_at"), table_name="category_types")
    op.drop_table("category_types")
    # ### end Alembic commands ###
