"""add master cruds fields and values

A small dynamic-content system in three tables.

`master_crud_fields` defines the questions a category asks; `master_cruds` is
one record filed under a category; `master_crud_field_values` holds one
record's answer to one field. Adding a question is therefore a row rather than
a migration, which is the point of the arrangement.

The category is what ties them together: a record may only answer fields
defined on its own category. A foreign key can name a table but never a subset
of one, so `app.modules.master_cruds.services.master_crud` is what enforces
that, along with "every required field was answered" and "the answer parses as
its declared type".

Foreign key behaviours, each chosen rather than defaulted:

- `category_id` on both parent tables is `RESTRICT`, matching the categories
  module: retiring a category must not take its records, nor the field
  definitions that give their values meaning.
- `master_crud_field_values.master_crud_id` is `CASCADE`: an answer describes
  its record and means nothing without it. Records are soft deleted, so this
  only fires on a purge.
- `master_crud_field_values.master_crud_field_id` is `RESTRICT` - the
  specified rule. A field that records have answered cannot be deleted; the
  service refuses first and says how many answers are in the way.
- `created_by` and `updated_by` are `SET NULL`, so closing an account does not
  delete what it wrote.

`value` is text whatever the field's type. One column cannot be four types at
once, and a column per type - three of them null on every row - is worse to
read and worse to query. `master_cruds.order` carries a `CHECK (> 0)` because
it was specified as a positive number.

Revision ID: 945488541a49
Revises: 4459a94650fb
Create Date: 2026-08-18 16:01:27.818651

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "945488541a49"
down_revision: str | None = "4459a94650fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "master_crud_fields",
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=150), nullable=False),
        sa.Column(
            "field_type", sa.String(length=20), server_default="text", nullable=False
        ),
        sa.Column(
            "field_requiredness", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "status", sa.String(length=20), server_default="active", nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_master_crud_fields_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_master_crud_fields_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_master_crud_fields_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_master_crud_fields")),
        sa.UniqueConstraint(
            "category_id", "field_name", name="uq_master_crud_fields_category_name"
        ),
    )
    op.create_index(
        op.f("ix_master_crud_fields_category_id"),
        "master_crud_fields",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_master_crud_fields_deleted_at"),
        "master_crud_fields",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_master_crud_fields_status"),
        "master_crud_fields",
        ["status"],
        unique=False,
    )
    op.create_table(
        "master_cruds",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("order", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="active", nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint('"order" > 0', name=op.f("ck_master_cruds_order_positive")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_master_cruds_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_master_cruds_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_master_cruds_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_master_cruds")),
    )
    op.create_index(
        op.f("ix_master_cruds_category_id"),
        "master_cruds",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        "ix_master_cruds_category_id_order",
        "master_cruds",
        ["category_id", "order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_master_cruds_deleted_at"), "master_cruds", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_master_cruds_slug"), "master_cruds", ["slug"], unique=True)
    op.create_index(
        op.f("ix_master_cruds_status"), "master_cruds", ["status"], unique=False
    )
    op.create_table(
        "master_crud_field_values",
        sa.Column("master_crud_id", sa.UUID(), nullable=False),
        sa.Column("master_crud_field_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["master_crud_field_id"],
            ["master_crud_fields.id"],
            name=op.f(
                "fk_master_crud_field_values_master_crud_field_id_master_crud_fields"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["master_crud_id"],
            ["master_cruds.id"],
            name=op.f("fk_master_crud_field_values_master_crud_id_master_cruds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_master_crud_field_values")),
        sa.UniqueConstraint(
            "master_crud_id",
            "master_crud_field_id",
            name="uq_master_crud_field_values_record_field",
        ),
    )
    op.create_index(
        op.f("ix_master_crud_field_values_master_crud_field_id"),
        "master_crud_field_values",
        ["master_crud_field_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_master_crud_field_values_master_crud_field_id"),
        table_name="master_crud_field_values",
    )
    op.drop_table("master_crud_field_values")
    op.drop_index(op.f("ix_master_cruds_status"), table_name="master_cruds")
    op.drop_index(op.f("ix_master_cruds_slug"), table_name="master_cruds")
    op.drop_index(op.f("ix_master_cruds_deleted_at"), table_name="master_cruds")
    op.drop_index("ix_master_cruds_category_id_order", table_name="master_cruds")
    op.drop_index(op.f("ix_master_cruds_category_id"), table_name="master_cruds")
    op.drop_table("master_cruds")
    op.drop_index(op.f("ix_master_crud_fields_status"), table_name="master_crud_fields")
    op.drop_index(
        op.f("ix_master_crud_fields_deleted_at"), table_name="master_crud_fields"
    )
    op.drop_index(
        op.f("ix_master_crud_fields_category_id"), table_name="master_crud_fields"
    )
    op.drop_table("master_crud_fields")
    # ### end Alembic commands ###
