"""initial baseline

Revision ID: df82b30d3416
Revises:
Create Date: 2026-08-15 10:24:09.886373

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "df82b30d3416"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
