"""add menus table

One navigation item: a title, a link, an optional icon and image, and a place
in a tree.

Which navigation an item belongs to is not a column of its own. It is
`menu_category_id`, a row in `categories` from the Menu Category taxonomy that
the next revision seeds - one vocabulary, managed in one place, in a tree the
categories module already knows how to nest, rename and retire. A foreign key
can name a table but never a subset of one, so `app.modules.menus.services.menu`
is what holds that restriction.

Foreign key behaviours, each chosen rather than defaulted:

- `parent_id` and `menu_category_id` are `RESTRICT`, matching the categories
  module: removing a parent or retiring a category must not silently take a
  whole branch of a live navigation with it. The service refuses first and
  says what is in the way.
- `created_by` and `updated_by` are `SET NULL`, so closing the account of
  whoever built a navigation does not delete the navigation.

`order` carries a `CHECK (> 0)` because it was specified as a positive number.
The request schema rejects zero and below already; the constraint catches the
writes that never pass through one.

Revision ID: 5250e9d445c9
Revises: c4f1a2d8e6b3
Create Date: 2026-08-18 10:35:55.226296

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5250e9d445c9"
down_revision: str | None = "c4f1a2d8e6b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menus",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("image", sa.String(length=500), nullable=True),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("menu_category_id", sa.UUID(), nullable=False),
        sa.Column("order", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_menus_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["menu_category_id"],
            ["categories.id"],
            name=op.f("fk_menus_menu_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["menus.id"],
            name=op.f("fk_menus_parent_id_menus"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_menus_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_menus")),
        sa.CheckConstraint('"order" > 0', name=op.f("ck_menus_order_positive")),
    )
    op.create_index(op.f("ix_menus_deleted_at"), "menus", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_menus_menu_category_id"), "menus", ["menu_category_id"], unique=False
    )
    op.create_index(
        "ix_menus_menu_category_id_order",
        "menus",
        ["menu_category_id", "order"],
        unique=False,
    )
    op.create_index(
        "ix_menus_parent_id_order", "menus", ["parent_id", "order"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_menus_parent_id_order", table_name="menus")
    op.drop_index("ix_menus_menu_category_id_order", table_name="menus")
    op.drop_index(op.f("ix_menus_menu_category_id"), table_name="menus")
    op.drop_index(op.f("ix_menus_deleted_at"), table_name="menus")
    op.drop_table("menus")
    # ### end Alembic commands ###
