"""add password reset tokens

Adds the table behind password recovery, and the one setting the reset link
needs: where the frontend's "choose a new password" page lives.

Revision ID: 5db4c480c161
Revises: e772640a005f
Create Date: 2026-08-15 17:11:19.048636

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5db4c480c161"
down_revision: str | None = "e772640a005f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_ip", sa.String(length=45), nullable=True),
        sa.Column("requested_via", sa.String(length=20), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_reset_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
        sa.UniqueConstraint(
            "token_hash", name=op.f("uq_password_reset_tokens_token_hash")
        ),
    )
    # Serves both the throttle and "retire the older links", which each ask
    # for one user's recent rows.
    op.create_index(
        "ix_password_reset_tokens_user_id_created_at",
        "password_reset_tokens",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    _seed_reset_path_setting()


def _seed_reset_path_setting() -> None:
    """Add the setting a reset link is built from.

    Values are literal rather than imported from the settings module: a
    migration has to keep applying the same data even after the application
    code moves on.
    """
    op.get_bind().execute(
        sa.text("""
            INSERT INTO settings (
                key, value, value_type, "group", label, description,
                is_secret, is_system
            )
            VALUES (
                'password_reset_path', '/reset-password', 'string', 'general',
                'Password reset page',
                'Frontend page a reset link points at. The token is appended '
                'as `?token=`.',
                false, true
            )
            ON CONFLICT (key) DO NOTHING
            """)
    )


def downgrade() -> None:
    """Revert this revision."""
    op.get_bind().execute(
        sa.text("DELETE FROM settings WHERE key = 'password_reset_path'")
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_password_reset_tokens_user_id_created_at",
        table_name="password_reset_tokens",
    )
    op.drop_table("password_reset_tokens")
    # ### end Alembic commands ###
