"""add blogs and blog tags

The post itself, and the table linking it to its tags.

A post's category and tags are rows in `categories`, not tables of their own:
the category comes from the `blog_category` taxonomy and the tags from
`blog_tag`, both seeded by the next revision. A foreign key can only name a
table, never a subset of it, so the service is what holds those two vocabularies
apart - see `app.modules.blogs.services.blog`.

Foreign key behaviours, each chosen rather than defaulted:

- `blog_category_id` and `blog_tags.tag_id` are `RESTRICT`, matching the
  categories module: retiring a category must not take the posts filed under
  it, and the service says what is in the way first.
- `author_id`, `created_by` and `updated_by` are `SET NULL`, so closing an
  account does not delete what it wrote. A byline outliving the account is
  the normal case, not an edge one.
- `blog_tags.blog_id` is `CASCADE`: those rows describe a post and mean
  nothing without it. Posts are soft deleted, so this only fires on a purge.

The `meta_*` and `og_*` columns come from `SEOFieldsMixin`, shared with the
CMS pages and course pages still to come, so the three cannot drift apart.

Revision ID: 1ec7fb0c4bb7
Revises: b273e1cb0395
Create Date: 2026-08-15 18:52:24.900280

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ec7fb0c4bb7"
down_revision: str | None = "b273e1cb0395"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blogs",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("excerpt", sa.String(length=500), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("featured_image_url", sa.String(length=500), nullable=True),
        sa.Column("featured_image_alt", sa.String(length=255), nullable=True),
        sa.Column("blog_category_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("reading_minutes", sa.Integer(), server_default="1", nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta_title", sa.String(length=255), nullable=True),
        sa.Column("meta_description", sa.String(length=500), nullable=True),
        sa.Column("meta_keywords", sa.String(length=255), nullable=True),
        sa.Column("canonical_url", sa.String(length=500), nullable=True),
        sa.Column("og_title", sa.String(length=255), nullable=True),
        sa.Column("og_description", sa.Text(), nullable=True),
        sa.Column("og_image_url", sa.String(length=500), nullable=True),
        sa.Column(
            "meta_robots",
            sa.String(length=100),
            server_default=sa.text("'index, follow'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_blogs_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["blog_category_id"],
            ["categories.id"],
            name=op.f("fk_blogs_blog_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_blogs_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_blogs_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blogs")),
    )
    op.create_index(op.f("ix_blogs_author_id"), "blogs", ["author_id"], unique=False)
    op.create_index(
        op.f("ix_blogs_blog_category_id"), "blogs", ["blog_category_id"], unique=False
    )
    op.create_index(op.f("ix_blogs_deleted_at"), "blogs", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_blogs_published_at"), "blogs", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_blogs_slug"), "blogs", ["slug"], unique=True)
    op.create_index(op.f("ix_blogs_status"), "blogs", ["status"], unique=False)
    op.create_index(
        "ix_blogs_status_published_at",
        "blogs",
        ["status", "published_at"],
        unique=False,
    )
    op.create_table(
        "blog_tags",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("blog_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["blog_id"],
            ["blogs.id"],
            name=op.f("fk_blog_tags_blog_id_blogs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["categories.id"],
            name=op.f("fk_blog_tags_tag_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blog_tags")),
        sa.UniqueConstraint("blog_id", "tag_id", name="uq_blog_tags_blog_tag"),
    )
    op.create_index("ix_blog_tags_tag_id", "blog_tags", ["tag_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_blog_tags_tag_id", table_name="blog_tags")
    op.drop_table("blog_tags")
    op.drop_index("ix_blogs_status_published_at", table_name="blogs")
    op.drop_index(op.f("ix_blogs_status"), table_name="blogs")
    op.drop_index(op.f("ix_blogs_slug"), table_name="blogs")
    op.drop_index(op.f("ix_blogs_published_at"), table_name="blogs")
    op.drop_index(op.f("ix_blogs_deleted_at"), table_name="blogs")
    op.drop_index(op.f("ix_blogs_blog_category_id"), table_name="blogs")
    op.drop_index(op.f("ix_blogs_author_id"), table_name="blogs")
    op.drop_table("blogs")
    # ### end Alembic commands ###
