"""add translations table

Revision ID: 4423c74e9402
Revises: df82b30d3416
Create Date: 2026-08-15 11:04:34.440564

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4423c74e9402"
down_revision: str | None = "df82b30d3416"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translations",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("namespace", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_translations")),
        sa.UniqueConstraint("key", "language", name="uq_translations_key_language"),
    )
    op.create_index(
        "ix_translations_language_namespace",
        "translations",
        ["language", "namespace"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_translations_language_namespace", table_name="translations")
    op.drop_table("translations")
    # ### end Alembic commands ###
