"""add course contents, reviews, certificate templates, projects, job successes and faqs

Revision ID: 8b25cf7dfd34
Revises: 9a1f5c7e3b82
Create Date: 2026-08-24 15:23:01.375044

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8b25cf7dfd34"
down_revision: str | None = "9a1f5c7e3b82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificate_templates",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "template_type",
            sa.String(length=20),
            server_default="completion",
            nullable=False,
        ),
        sa.Column(
            "orientation",
            sa.String(length=20),
            server_default="landscape",
            nullable=False,
        ),
        sa.Column(
            "page_size", sa.String(length=20), server_default="a4", nullable=False
        ),
        sa.Column("width_mm", sa.Integer(), nullable=True),
        sa.Column("height_mm", sa.Integer(), nullable=True),
        sa.Column("html_content", sa.Text(), nullable=True),
        sa.Column("css_content", sa.Text(), nullable=True),
        sa.Column("placeholders", sa.JSON(), nullable=True),
        sa.Column("design_config", sa.JSON(), nullable=True),
        sa.Column("background_image_url", sa.String(length=500), nullable=True),
        sa.Column("border_image_url", sa.String(length=500), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("seal_image_url", sa.String(length=500), nullable=True),
        sa.Column("preview_image_url", sa.String(length=500), nullable=True),
        sa.Column("font_family", sa.String(length=100), nullable=True),
        sa.Column("heading_font_family", sa.String(length=100), nullable=True),
        sa.Column("primary_color", sa.String(length=20), nullable=True),
        sa.Column("secondary_color", sa.String(length=20), nullable=True),
        sa.Column("text_color", sa.String(length=20), nullable=True),
        sa.Column("background_color", sa.String(length=20), nullable=True),
        sa.Column("signature_image_url", sa.String(length=500), nullable=True),
        sa.Column("signature_name", sa.String(length=150), nullable=True),
        sa.Column("signature_designation", sa.String(length=255), nullable=True),
        sa.Column("second_signature_image_url", sa.String(length=500), nullable=True),
        sa.Column("second_signature_name", sa.String(length=150), nullable=True),
        sa.Column("second_signature_designation", sa.String(length=255), nullable=True),
        sa.Column("issuer_name", sa.String(length=150), nullable=True),
        sa.Column("organization_name", sa.String(length=255), nullable=True),
        sa.Column("organization_address", sa.Text(), nullable=True),
        sa.Column("certificate_number_prefix", sa.String(length=50), nullable=True),
        sa.Column("certificate_number_format", sa.String(length=100), nullable=True),
        sa.Column(
            "verification_enabled", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("verification_url_pattern", sa.String(length=500), nullable=True),
        sa.Column(
            "qr_code_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("qr_code_position", sa.String(length=20), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_certificate_templates_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_certificate_templates_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificate_templates")),
    )
    op.create_index(
        op.f("ix_certificate_templates_code"),
        "certificate_templates",
        ["code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_certificate_templates_deleted_at"),
        "certificate_templates",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_certificate_templates_status"),
        "certificate_templates",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_certificate_templates_status_is_active",
        "certificate_templates",
        ["status", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_certificate_templates_template_type"),
        "certificate_templates",
        ["template_type"],
        unique=False,
    )
    op.create_table(
        "course_contents",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "content_type", sa.String(length=20), server_default="video", nullable=False
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duration_seconds", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_preview", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_mandatory", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "is_downloadable", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("available_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_after_days", sa.Integer(), nullable=True),
        sa.Column("video_url", sa.String(length=500), nullable=True),
        sa.Column("video_provider", sa.String(length=20), nullable=True),
        sa.Column("video_id", sa.String(length=255), nullable=True),
        sa.Column("video_thumbnail", sa.String(length=500), nullable=True),
        sa.Column("video_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("video_quality", sa.String(length=20), nullable=True),
        sa.Column("video_subtitles", sa.JSON(), nullable=True),
        sa.Column("video_transcript", sa.Text(), nullable=True),
        sa.Column("live_provider", sa.String(length=20), nullable=True),
        sa.Column("live_meeting_url", sa.String(length=500), nullable=True),
        sa.Column("live_meeting_id", sa.String(length=255), nullable=True),
        sa.Column("live_passcode", sa.String(length=100), nullable=True),
        sa.Column("live_start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("live_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("live_timezone", sa.String(length=64), nullable=True),
        sa.Column("live_status", sa.String(length=20), nullable=True),
        sa.Column("live_host_id", sa.UUID(), nullable=True),
        sa.Column("live_max_participants", sa.Integer(), nullable=True),
        sa.Column("live_recording_url", sa.String(length=500), nullable=True),
        sa.Column(
            "live_is_recorded", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("file_type", sa.String(length=20), nullable=True),
        sa.Column("file_mime_type", sa.String(length=150), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("file_page_count", sa.Integer(), nullable=True),
        sa.Column("file_thumbnail", sa.String(length=500), nullable=True),
        sa.Column("quiz_instructions", sa.Text(), nullable=True),
        sa.Column("quiz_time_limit_minutes", sa.Integer(), nullable=True),
        sa.Column("quiz_passing_score", sa.Integer(), nullable=True),
        sa.Column("quiz_max_attempts", sa.Integer(), nullable=True),
        sa.Column(
            "quiz_total_questions", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("quiz_total_marks", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "quiz_negative_marking",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "quiz_shuffle_questions",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "quiz_show_correct_answers",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.Column("quiz_questions", sa.JSON(), nullable=True),
        sa.Column("content_data", sa.JSON(), nullable=True),
        sa.Column("attachments", sa.JSON(), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_course_contents_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_course_contents_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["live_host_id"],
            ["users.id"],
            name=op.f("fk_course_contents_live_host_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["course_contents.id"],
            name=op.f("fk_course_contents_parent_id_course_contents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_course_contents_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_contents")),
    )
    op.create_index(
        op.f("ix_course_contents_content_type"),
        "course_contents",
        ["content_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_contents_course_id"),
        "course_contents",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        "ix_course_contents_course_id_content_type",
        "course_contents",
        ["course_id", "content_type"],
        unique=False,
    )
    op.create_index(
        "ix_course_contents_course_id_sort_order",
        "course_contents",
        ["course_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_contents_deleted_at"),
        "course_contents",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_contents_live_start_at"),
        "course_contents",
        ["live_start_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_contents_parent_id"),
        "course_contents",
        ["parent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_contents_slug"), "course_contents", ["slug"], unique=False
    )
    op.create_index(
        op.f("ix_course_contents_status"), "course_contents", ["status"], unique=False
    )
    op.create_table(
        "course_faqs",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.String(length=500), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("faq_group", sa.String(length=100), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("view_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("helpful_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("unhelpful_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_course_faqs_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_course_faqs_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_course_faqs_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_faqs")),
    )
    op.create_index(
        op.f("ix_course_faqs_course_id"), "course_faqs", ["course_id"], unique=False
    )
    op.create_index(
        "ix_course_faqs_course_id_sort_order",
        "course_faqs",
        ["course_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_faqs_deleted_at"), "course_faqs", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_course_faqs_faq_group"), "course_faqs", ["faq_group"], unique=False
    )
    op.create_index(
        op.f("ix_course_faqs_status"), "course_faqs", ["status"], unique=False
    )
    op.create_table(
        "job_successes",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=True),
        sa.Column("student_name", sa.String(length=150), nullable=False),
        sa.Column("student_email", sa.String(length=255), nullable=True),
        sa.Column("student_phone", sa.String(length=30), nullable=True),
        sa.Column("student_photo", sa.String(length=500), nullable=True),
        sa.Column("student_linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("batch_name", sa.String(length=100), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("company_logo_url", sa.String(length=500), nullable=True),
        sa.Column("company_website", sa.String(length=500), nullable=True),
        sa.Column("industry", sa.String(length=150), nullable=True),
        sa.Column("job_title", sa.String(length=255), nullable=False),
        sa.Column(
            "job_type", sa.String(length=20), server_default="full_time", nullable=False
        ),
        sa.Column(
            "work_mode", sa.String(length=20), server_default="onsite", nullable=False
        ),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=150), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("salary_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("salary_min", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "salary_currency", sa.String(length=3), server_default="USD", nullable=False
        ),
        sa.Column(
            "salary_period",
            sa.String(length=20),
            server_default="monthly",
            nullable=False,
        ),
        sa.Column(
            "is_salary_public", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("previous_role", sa.String(length=255), nullable=True),
        sa.Column("previous_company", sa.String(length=255), nullable=True),
        sa.Column("hired_at", sa.Date(), nullable=True),
        sa.Column("days_to_hire", sa.Integer(), nullable=True),
        sa.Column("story", sa.Text(), nullable=True),
        sa.Column("quote", sa.Text(), nullable=True),
        sa.Column("video_url", sa.String(length=500), nullable=True),
        sa.Column("is_featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_job_successes_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_job_successes_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_job_successes_student_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_job_successes_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
            name=op.f("fk_job_successes_verified_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_successes")),
    )
    op.create_index(
        op.f("ix_job_successes_company_name"),
        "job_successes",
        ["company_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_successes_course_id"), "job_successes", ["course_id"], unique=False
    )
    op.create_index(
        "ix_job_successes_course_id_status",
        "job_successes",
        ["course_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_successes_deleted_at"),
        "job_successes",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_successes_hired_at"), "job_successes", ["hired_at"], unique=False
    )
    op.create_index(
        op.f("ix_job_successes_status"), "job_successes", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_job_successes_student_id"),
        "job_successes",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=True),
        sa.Column("short_description", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("features", sa.JSON(), nullable=True),
        sa.Column("technologies", sa.JSON(), nullable=True),
        sa.Column("tools", sa.JSON(), nullable=True),
        sa.Column("deliverables", sa.JSON(), nullable=True),
        sa.Column("evaluation_criteria", sa.JSON(), nullable=True),
        sa.Column("thumbnail", sa.String(length=500), nullable=True),
        sa.Column("cover_image", sa.String(length=500), nullable=True),
        sa.Column("images", sa.JSON(), nullable=True),
        sa.Column("demo_url", sa.String(length=500), nullable=True),
        sa.Column("source_code_url", sa.String(length=500), nullable=True),
        sa.Column("video_url", sa.String(length=500), nullable=True),
        sa.Column(
            "project_type",
            sa.String(length=20),
            server_default="individual",
            nullable=False,
        ),
        sa.Column("difficulty_level", sa.String(length=20), nullable=True),
        sa.Column("estimated_hours", sa.Integer(), nullable=True),
        sa.Column("max_score", sa.Integer(), nullable=True),
        sa.Column("is_mandatory", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_projects_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_projects_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_projects_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(
        op.f("ix_projects_course_id"), "projects", ["course_id"], unique=False
    )
    op.create_index(
        "ix_projects_course_id_sort_order",
        "projects",
        ["course_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_projects_deleted_at"), "projects", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=False)
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("reviewer_name", sa.String(length=150), nullable=True),
        sa.Column("reviewer_email", sa.String(length=255), nullable=True),
        sa.Column("reviewer_designation", sa.String(length=255), nullable=True),
        sa.Column("reviewer_avatar", sa.String(length=500), nullable=True),
        sa.Column("rating", sa.Numeric(precision=2, scale=1), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("video_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column("source", sa.String(length=20), server_default="web", nullable=False),
        sa.Column("is_featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "is_verified_purchase", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("moderated_by", sa.UUID(), nullable=True),
        sa.Column("moderated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("helpful_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("unhelpful_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("report_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reply", sa.Text(), nullable=True),
        sa.Column("replied_by", sa.UUID(), nullable=True),
        sa.Column("replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5", name=op.f("ck_reviews_review_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_reviews_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["moderated_by"],
            ["users.id"],
            name=op.f("fk_reviews_moderated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["replied_by"],
            ["users.id"],
            name=op.f("fk_reviews_replied_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_reviews_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
    )
    op.create_index(
        op.f("ix_reviews_course_id"), "reviews", ["course_id"], unique=False
    )
    op.create_index(
        "ix_reviews_course_id_status", "reviews", ["course_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_reviews_deleted_at"), "reviews", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_reviews_rating"), "reviews", ["rating"], unique=False)
    op.create_index(op.f("ix_reviews_status"), "reviews", ["status"], unique=False)
    op.create_index(op.f("ix_reviews_user_id"), "reviews", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reviews_user_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_status"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_rating"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_deleted_at"), table_name="reviews")
    op.drop_index("ix_reviews_course_id_status", table_name="reviews")
    op.drop_index(op.f("ix_reviews_course_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_index(op.f("ix_projects_deleted_at"), table_name="projects")
    op.drop_index("ix_projects_course_id_sort_order", table_name="projects")
    op.drop_index(op.f("ix_projects_course_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_job_successes_student_id"), table_name="job_successes")
    op.drop_index(op.f("ix_job_successes_status"), table_name="job_successes")
    op.drop_index(op.f("ix_job_successes_hired_at"), table_name="job_successes")
    op.drop_index(op.f("ix_job_successes_deleted_at"), table_name="job_successes")
    op.drop_index("ix_job_successes_course_id_status", table_name="job_successes")
    op.drop_index(op.f("ix_job_successes_course_id"), table_name="job_successes")
    op.drop_index(op.f("ix_job_successes_company_name"), table_name="job_successes")
    op.drop_table("job_successes")
    op.drop_index(op.f("ix_course_faqs_status"), table_name="course_faqs")
    op.drop_index(op.f("ix_course_faqs_faq_group"), table_name="course_faqs")
    op.drop_index(op.f("ix_course_faqs_deleted_at"), table_name="course_faqs")
    op.drop_index("ix_course_faqs_course_id_sort_order", table_name="course_faqs")
    op.drop_index(op.f("ix_course_faqs_course_id"), table_name="course_faqs")
    op.drop_table("course_faqs")
    op.drop_index(op.f("ix_course_contents_status"), table_name="course_contents")
    op.drop_index(op.f("ix_course_contents_slug"), table_name="course_contents")
    op.drop_index(op.f("ix_course_contents_parent_id"), table_name="course_contents")
    op.drop_index(
        op.f("ix_course_contents_live_start_at"), table_name="course_contents"
    )
    op.drop_index(op.f("ix_course_contents_deleted_at"), table_name="course_contents")
    op.drop_index(
        "ix_course_contents_course_id_sort_order", table_name="course_contents"
    )
    op.drop_index(
        "ix_course_contents_course_id_content_type", table_name="course_contents"
    )
    op.drop_index(op.f("ix_course_contents_course_id"), table_name="course_contents")
    op.drop_index(op.f("ix_course_contents_content_type"), table_name="course_contents")
    op.drop_table("course_contents")
    op.drop_index(
        op.f("ix_certificate_templates_template_type"),
        table_name="certificate_templates",
    )
    op.drop_index(
        "ix_certificate_templates_status_is_active", table_name="certificate_templates"
    )
    op.drop_index(
        op.f("ix_certificate_templates_status"), table_name="certificate_templates"
    )
    op.drop_index(
        op.f("ix_certificate_templates_deleted_at"), table_name="certificate_templates"
    )
    op.drop_index(
        op.f("ix_certificate_templates_code"), table_name="certificate_templates"
    )
    op.drop_table("certificate_templates")
    # ### end Alembic commands ###
