"""add pages table

Standalone CMS content addressed by its slug - "About us", a privacy policy, a
landing page.

The `meta_*` and `og_*` columns come from `SEOFieldsMixin`, the same mixin the
blogs table uses and the course pages still to come will use, so the three
cannot drift apart. A `meta_tag` box in an editor writes to `meta_keywords`;
the read schema fills in whatever an author left blank, deriving the meta title
from the title and the description from the summary.

`created_by` and `updated_by` are `SET NULL`: closing an account must not
delete the pages it wrote.

No permissions are seeded. `page.view`, `page.create`, `page.update`,
`page.delete` and `page.publish` were seeded with the platform's original
permission set and granted to the roles that hold the equivalent blog codes -
this table is the thing they were always describing.

Revision ID: 194781c7a53f
Revises: 15e2aac57903
Create Date: 2026-08-18 17:01:03.899364

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "194781c7a53f"
down_revision: str | None = "15e2aac57903"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pages",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("thumbnail_image", sa.String(length=500), nullable=True),
        sa.Column("thumbnail_image_alt", sa.String(length=255), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta_title", sa.String(length=255), nullable=True),
        sa.Column("meta_description", sa.String(length=500), nullable=True),
        sa.Column("meta_keywords", sa.String(length=255), nullable=True),
        sa.Column("canonical_url", sa.String(length=500), nullable=True),
        sa.Column("og_title", sa.String(length=255), nullable=True),
        sa.Column("og_description", sa.Text(), nullable=True),
        sa.Column("og_image_url", sa.String(length=500), nullable=True),
        sa.Column(
            "meta_robots",
            sa.String(length=100),
            server_default=sa.text("'index, follow'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_pages_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_pages_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
    )
    op.create_index(op.f("ix_pages_deleted_at"), "pages", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_pages_published_at"), "pages", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_pages_slug"), "pages", ["slug"], unique=True)
    op.create_index(op.f("ix_pages_status"), "pages", ["status"], unique=False)
    op.create_index(
        "ix_pages_status_published_at",
        "pages",
        ["status", "published_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pages_status_published_at", table_name="pages")
    op.drop_index(op.f("ix_pages_status"), table_name="pages")
    op.drop_index(op.f("ix_pages_slug"), table_name="pages")
    op.drop_index(op.f("ix_pages_published_at"), table_name="pages")
    op.drop_index(op.f("ix_pages_deleted_at"), table_name="pages")
    op.drop_table("pages")
    # ### end Alembic commands ###
