"""add contact inquiries table permissions and settings

Revision ID: bb92478a20b1
Revises: 766818affd8d
Create Date: 2026-08-24 17:08:18.695961

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb92478a20b1"
down_revision: str | None = "766818affd8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


INQUIRY_PERMISSIONS = [
    ("inquiry.view", "view", "View contact inquiries"),
    ("inquiry.update", "update", "Update contact inquiries"),
    ("inquiry.delete", "delete", "Delete contact inquiries"),
    ("inquiry.export", "export", "Export contact inquiries"),
]

ALL_INQUIRY_CODES = [code for code, *_ in INQUIRY_PERMISSIONS]

#: An inquiry is a member of the public's name, email and phone number, so
#: the grants are narrower than a content module's: the roles that actually
#: work the enquiry inbox get it, and nobody else needs a copy. There is no
#: create permission - the only thing that creates an inquiry is the public
#: form, and it is not authenticated.
INQUIRY_GRANTS = {
    "super-admin": ALL_INQUIRY_CODES,
    "admin": ALL_INQUIRY_CODES,
    "support": ["inquiry.view", "inquiry.update"],
    "content-manager": ["inquiry.view"],
}

INQUIRY_SETTINGS = [
    (
        "contact_inquiry_rate_limit_max",
        "5",
        "integer",
        "Contact form submissions per window",
        "How many inquiries one address may submit inside the window below. "
        "0 disables the limit.",
    ),
    (
        "contact_inquiry_rate_limit_window_minutes",
        "15",
        "integer",
        "Contact form rate limit window (minutes)",
        "How long the submission count above is measured over.",
    ),
    (
        "contact_inquiry_notify_email",
        None,
        "string",
        "Contact inquiry notification address",
        "Where the new inquiry notification is sent. Blank disables it.",
    ),
    (
        "contact_inquiry_acknowledge_submitter",
        "true",
        "boolean",
        "Acknowledge contact form submissions",
        "Whether the visitor receives a confirmation that their inquiry "
        "was received.",
    ),
]


def _seed(connection: sa.Connection) -> None:
    """Insert the permissions, grants and settings this module reads.

    Every statement is idempotent, so running this against a database that
    already carries some of these rows is a no-op rather than an integrity
    error.
    """
    for code, action, name in INQUIRY_PERMISSIONS:
        connection.execute(
            sa.text("""
                INSERT INTO permissions (code, resource, action, name, is_system)
                VALUES (:code, 'inquiry', :action, :name, true)
                ON CONFLICT (code) DO NOTHING
                """),
            {"code": code, "action": action, "name": name},
        )

    for slug, codes in INQUIRY_GRANTS.items():
        connection.execute(
            sa.text("""
                INSERT INTO role_permissions (role_id, permission_id)
                SELECT r.id, p.id FROM roles r JOIN permissions p ON true
                WHERE r.slug = :slug AND p.code = ANY(:codes)
                ON CONFLICT DO NOTHING
                """),
            {"slug": slug, "codes": codes},
        )

    for key, value, value_type, label, description in INQUIRY_SETTINGS:
        connection.execute(
            sa.text("""
                INSERT INTO settings (
                    key, value, value_type, "group", label, description,
                    is_secret, is_system
                )
                VALUES (
                    :key, :value, :value_type, 'general', :label, :description,
                    false, true
                )
                ON CONFLICT (key) DO NOTHING
                """),
            {
                "key": key,
                "value": value,
                "value_type": value_type,
                "label": label,
                "description": description,
            },
        )


def _unseed(connection: sa.Connection) -> None:
    """Remove what `_seed` added, innermost references first."""
    connection.execute(
        sa.text("DELETE FROM settings WHERE key = ANY(:keys)"),
        {"keys": [key for key, *_ in INQUIRY_SETTINGS]},
    )
    connection.execute(sa.text("""
            DELETE FROM role_permissions
            WHERE permission_id IN (
                SELECT id FROM permissions WHERE resource = 'inquiry'
            )
            """))
    connection.execute(sa.text("DELETE FROM permissions WHERE resource = 'inquiry'"))


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_inquiries",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=False),
        sa.Column("interested_in", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), server_default="new", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=100), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["read_by"],
            ["users.id"],
            name=op.f("fk_contact_inquiries_read_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_contact_inquiries_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_inquiries")),
    )
    op.create_index(
        "ix_contact_inquiries_created_at",
        "contact_inquiries",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_inquiries_deleted_at"),
        "contact_inquiries",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_inquiries_email"), "contact_inquiries", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_contact_inquiries_interested_in"),
        "contact_inquiries",
        ["interested_in"],
        unique=False,
    )
    op.create_index(
        "ix_contact_inquiries_ip_address_created_at",
        "contact_inquiries",
        ["ip_address", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_inquiries_is_read"),
        "contact_inquiries",
        ["is_read"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contact_inquiries_phone"), "contact_inquiries", ["phone"], unique=False
    )
    op.create_index(
        op.f("ix_contact_inquiries_status"),
        "contact_inquiries",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_contact_inquiries_status_created_at",
        "contact_inquiries",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    _seed(op.get_bind())


def downgrade() -> None:
    """Revert this revision."""
    _unseed(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_contact_inquiries_status_created_at", table_name="contact_inquiries"
    )
    op.drop_index(op.f("ix_contact_inquiries_status"), table_name="contact_inquiries")
    op.drop_index(op.f("ix_contact_inquiries_phone"), table_name="contact_inquiries")
    op.drop_index(op.f("ix_contact_inquiries_is_read"), table_name="contact_inquiries")
    op.drop_index(
        "ix_contact_inquiries_ip_address_created_at", table_name="contact_inquiries"
    )
    op.drop_index(
        op.f("ix_contact_inquiries_interested_in"), table_name="contact_inquiries"
    )
    op.drop_index(op.f("ix_contact_inquiries_email"), table_name="contact_inquiries")
    op.drop_index(
        op.f("ix_contact_inquiries_deleted_at"), table_name="contact_inquiries"
    )
    op.drop_index("ix_contact_inquiries_created_at", table_name="contact_inquiries")
    op.drop_table("contact_inquiries")
    # ### end Alembic commands ###
