"""add notifications and notification recipients

Revision ID: db079b9ec94c
Revises: bb92478a20b1
Create Date: 2026-08-24 18:05:17.813402

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "db079b9ec94c"
down_revision: str | None = "bb92478a20b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: `notification.view` and `notification.send` already exist - they were
#: seeded with the original permission set, before this module was built.
#: Only the write verbs are new, and the insert is idempotent so re-running
#: over the existing pair is a no-op.
NOTIFICATION_PERMISSIONS = [
    ("notification.create", "create", "Create notifications"),
    ("notification.update", "update", "Update notifications"),
    ("notification.delete", "delete", "Delete notifications"),
]

#: Authoring and withdrawing platform-wide announcements stays with
#: administrators. Support keeps the `view` and `send` it already had:
#: answering a learner's question does not extend to writing something every
#: account receives.
NOTIFICATION_GRANTS = {
    "super-admin": [code for code, *_ in NOTIFICATION_PERMISSIONS],
    "admin": [code for code, *_ in NOTIFICATION_PERMISSIONS],
}


def _seed(connection: sa.Connection) -> None:
    """Add the notification write permissions and grant them."""
    for code, action, name in NOTIFICATION_PERMISSIONS:
        connection.execute(
            sa.text("""
                INSERT INTO permissions (code, resource, action, name, is_system)
                VALUES (:code, 'notification', :action, :name, true)
                ON CONFLICT (code) DO NOTHING
                """),
            {"code": code, "action": action, "name": name},
        )

    for slug, codes in NOTIFICATION_GRANTS.items():
        connection.execute(
            sa.text("""
                INSERT INTO role_permissions (role_id, permission_id)
                SELECT r.id, p.id FROM roles r JOIN permissions p ON true
                WHERE r.slug = :slug AND p.code = ANY(:codes)
                ON CONFLICT DO NOTHING
                """),
            {"slug": slug, "codes": codes},
        )


def _unseed(connection: sa.Connection) -> None:
    """Remove only what `_seed` added.

    `notification.view` and `notification.send` predate this revision, so
    they are deliberately left alone - removing them would undo something
    this migration never did.
    """
    codes = [code for code, *_ in NOTIFICATION_PERMISSIONS]

    connection.execute(
        sa.text("""
            DELETE FROM role_permissions
            WHERE permission_id IN (
                SELECT id FROM permissions WHERE code = ANY(:codes)
            )
            """),
        {"codes": codes},
    )
    connection.execute(
        sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"), {"codes": codes}
    )


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("short_message", sa.Text(), nullable=False),
        sa.Column("details_content", sa.Text(), nullable=False),
        sa.Column(
            "notification_type",
            sa.String(length=50),
            server_default="admin",
            nullable=False,
        ),
        sa.Column(
            "delivery_type",
            sa.String(length=50),
            server_default="global",
            nullable=False,
        ),
        sa.Column("target_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "priority", sa.String(length=50), server_default="normal", nullable=False
        ),
        sa.Column("icon", sa.String(length=255), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column(
            "has_details_page", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_recipients", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_reads", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "total_detail_views", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_notifications_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_notifications_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_created_at", "notifications", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_created_by"),
        "notifications",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_deleted_at"),
        "notifications",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_delivery_type"),
        "notifications",
        ["delivery_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_expires_at"),
        "notifications",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_is_active"), "notifications", ["is_active"], unique=False
    )
    op.create_index(
        "ix_notifications_is_active_publish_at",
        "notifications",
        ["is_active", "publish_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_notification_type"),
        "notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_priority"), "notifications", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_publish_at"),
        "notifications",
        ["publish_at"],
        unique=False,
    )
    op.create_table(
        "notification_recipients",
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "delivered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "details_viewed", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "details_view_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("details_viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
            name=op.f("fk_notification_recipients_notification_id_notifications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_recipients_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_recipients")),
        sa.UniqueConstraint(
            "notification_id", "user_id", name="uq_notification_recipients_pair"
        ),
    )
    op.create_index(
        "ix_notification_recipients_created_at",
        "notification_recipients",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_recipients_details_viewed",
        "notification_recipients",
        ["details_viewed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_recipients_is_read"),
        "notification_recipients",
        ["is_read"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_recipients_notification_id"),
        "notification_recipients",
        ["notification_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_recipients_read_at"),
        "notification_recipients",
        ["read_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_recipients_user_id"),
        "notification_recipients",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_recipients_user_id_is_read",
        "notification_recipients",
        ["user_id", "is_read"],
        unique=False,
    )
    # ### end Alembic commands ###

    _seed(op.get_bind())


def downgrade() -> None:
    """Revert this revision."""
    _unseed(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_notification_recipients_user_id_is_read",
        table_name="notification_recipients",
    )
    op.drop_index(
        op.f("ix_notification_recipients_user_id"), table_name="notification_recipients"
    )
    op.drop_index(
        op.f("ix_notification_recipients_read_at"), table_name="notification_recipients"
    )
    op.drop_index(
        op.f("ix_notification_recipients_notification_id"),
        table_name="notification_recipients",
    )
    op.drop_index(
        op.f("ix_notification_recipients_is_read"), table_name="notification_recipients"
    )
    op.drop_index(
        "ix_notification_recipients_details_viewed",
        table_name="notification_recipients",
    )
    op.drop_index(
        "ix_notification_recipients_created_at", table_name="notification_recipients"
    )
    op.drop_table("notification_recipients")
    op.drop_index(op.f("ix_notifications_publish_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_priority"), table_name="notifications")
    op.drop_index(
        op.f("ix_notifications_notification_type"), table_name="notifications"
    )
    op.drop_index("ix_notifications_is_active_publish_at", table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_active"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_expires_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_delivery_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_deleted_at"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_by"), table_name="notifications")
    op.drop_index("ix_notifications_created_at", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
