"""Database engine, session management and the declarative `Base`.

Everything ORM-related starts here: the async engine bound to PostgreSQL, the
session factory, the request-scoped session dependency, and the `Base` class
every model inherits from.
"""

import logging
import re
import uuid
from collections.abc import AsyncIterator
from datetime import datetime

from sqlalchemy import DateTime, MetaData, NullPool, func, text
from sqlalchemy.dialects.postgresql import UUID as PgUUID  # noqa: N811
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

from app.core.config import settings

logger = logging.getLogger(__name__)

# Predictable constraint names, so Alembic autogenerate produces stable
# migrations instead of relying on PostgreSQL's generated identifiers.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

# Splits CamelCase into words, keeping acronyms together (CMSPage -> cms_page).
_CAMEL_BOUNDARY = re.compile(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")

_IRREGULAR_PLURALS = {
    "person": "people",
    "child": "children",
    "man": "men",
    "woman": "women",
    "datum": "data",
    "index": "indexes",
    "quiz": "quizzes",
}


def to_snake_case(name: str) -> str:
    """`CourseModule` -> `course_module`, `CMSPage` -> `cms_page`."""
    return _CAMEL_BOUNDARY.sub("_", name).lower()


def pluralize(word: str) -> str:
    """Naive English pluralizer, applied to the last word of a snake_case name."""
    head, _, last = word.rpartition("_")
    prefix = f"{head}_" if head else ""

    if last in _IRREGULAR_PLURALS:
        return prefix + _IRREGULAR_PLURALS[last]
    if last.endswith("y") and not last.endswith(("ay", "ey", "iy", "oy", "uy")):
        return f"{prefix}{last[:-1]}ies"
    if last.endswith(("s", "x", "z", "ch", "sh")):
        return f"{prefix}{last}es"
    return f"{prefix}{last}s"


class Base(DeclarativeBase):
    """Declarative base for every model in the project.

    Table names are derived automatically as the snake_case plural of the class
    name, enforcing the project convention. A model can still set
    `__tablename__` explicitly when the generated name reads badly.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    @declared_attr.directive
    def __tablename__(cls) -> str:  # noqa: N805
        return pluralize(to_snake_case(cls.__name__))

    def __repr__(self) -> str:
        return f"<{type(self).__name__} id={getattr(self, 'id', None)}>"


class UUIDPrimaryKeyMixin:
    """UUID primary key generated by PostgreSQL, safe to expose in URLs."""

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """`created_at` / `updated_at`, both maintained by the database.

    `now()` is PostgreSQL's transaction timestamp, so every row touched by one
    transaction shares a value and `updated_at` advances between transactions
    rather than between statements. That consistency is the point: rows
    written together are timestamped together.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """Opt-in soft delete; repositories filter on `deleted_at IS NULL`."""

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), default=None, index=True
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None


def create_engine() -> AsyncEngine:
    """Build the async engine from centralized settings.

    Under `testing` the pool is switched off. A pooled connection belongs to
    the event loop that opened it, and the test suite runs more than one - the
    `TestClient` drives the app in its own loop, while async fixtures run in
    pytest's. Handing a connection from one to the other raises "attached to a
    different loop". A fresh connection per checkout costs nothing at test
    volumes and removes the hazard entirely.
    """
    if settings.is_testing:
        return create_async_engine(
            settings.database_url,
            echo=settings.db_echo,
            poolclass=NullPool,
            future=True,
        )

    return create_async_engine(
        settings.database_url,
        echo=settings.db_echo,
        pool_size=settings.db_pool_size,
        max_overflow=settings.db_max_overflow,
        pool_recycle=settings.db_pool_recycle_seconds,
        pool_pre_ping=True,
        future=True,
    )


engine: AsyncEngine = create_engine()

AsyncSessionFactory = async_sessionmaker(
    bind=engine,
    class_=AsyncSession,
    expire_on_commit=False,
    autoflush=False,
)


async def get_db() -> AsyncIterator[AsyncSession]:
    """Yield a request-scoped session.

    The session is rolled back and closed automatically. Committing is left to
    the service layer, which owns the transaction boundary - FastAPI runs this
    teardown after the response has been sent, so a commit here could fail
    silently with the client already told the request succeeded.
    """
    async with AsyncSessionFactory() as session:
        try:
            yield session
        except Exception:
            await session.rollback()
            raise


async def check_database_connection() -> bool:
    """Ping the database; used by the readiness probe."""
    try:
        async with engine.connect() as connection:
            await connection.execute(text("SELECT 1"))
    except SQLAlchemyError:
        logger.exception("Database connectivity check failed")
        return False
    return True


async def dispose_engine() -> None:
    """Close every pooled connection on shutdown."""
    await engine.dispose()
